### ISSUE TITLE
object 'troopdata' not found

### ISSUE THREAD

**Issue by bdwaldie** [meflynn/troopdata#5]
After successfully using the command 'troopdata' in the recent past, R now no longer recognizes the object troopdata. Here is replication code on colab https://colab.research.google.com/drive/120ItO38Uht3yX8apAZcR8ANjBoeFAgEE?usp=sharing

**Comment by meflynn** [comment]
Thanks for your patience! 

I think the problem here is that the `troopdata` object is no longer exported by the package, and has been replaced by `troopdata_rebuild_long` and `troopdata_rebuild_reports`. Because the new data have a mix of quarterly and yearly observations for some years the underlying data don't look like the original country-year format. To get a basic country-year dataset like the `troopdata` object you would need to write something like this:

```{r}
data <- troopdata::get_troopdata()
```

That should return a country-year data frame. Also note that the updated variable name for the total troop deployment figure is "troops_ad".
