### ISSUE TITLE
iraq 2006 & 2007

### ISSUE THREAD

**Issue by trhertling** [meflynn/troopdata#6]
Hello Mike,

I appreciate the updates incorporating 2024!

I noticed that the deployed numbers for troops_ad for Iraq are off for 2006 and 2007 (the "surge" timeframe).

2006 shows 423300 and 2007 shows 510000.

I believe the numbers should be closer to 170000.  They certainly never reached 1/2 million.

Also, is there a plan to incorporate rotational brigade combat team deployments (~4000 each) to Poland and South Korea?  They began in the 2014 timeframe.  

Thanks!

**Comment by meflynn** [comment]
Hi Todd (I assume)! Thanks for flagging this. There was indeed an issue where the values we used to estimate the Iraq-specific deployment numbers were being copied multiple times. Based on Reuters and FAS reports, we have 141100 for 2006 and 170000 for 2007. I think I have this ironed out and should be able to push an updated version to CRAN soon. In the meantime you should be able to download v1.0.1 from GitHub, and that should contain the fix.

I've though about trying to get rotational deployment data but haven't had time to locate a good source on that. If you have any tips please send them my way, because I'd love to include those! I usually have to give people the warning that the numbers aren't always an accurate reflection of the full extent of the US presence, and it would be nice to have more accurate numbers.
